### ISSUE TITLE
get survival working

### ISSUE THREAD

**Issue by CDRwojtek** [chromaticats/meta#36]
mmkay

So, as I see survival just got back up- there are issues with it atm. Here's a few.

- Unable to do any commands in survival, except /spawn
- You are able to teleport to players via being on the creative worlds, then /tp-ing or using spectator mode to get to another players location.
- Also, items just disappear when you use them

I think this is just the bulk of it, this is all the problems we have right now. Tschüss!

**Comment by CDRwojtek** [comment]
Sleeping doesn't work either app.

**Comment by jonthesquirrel** [comment]
@CDRwojtek Thanks for the list of issues, that's helpful to know what to fix! I will set aside some time soon to get this working.

**Comment by jonthesquirrel** [comment]
(mario): too many enchants gets cleared by a plugin: find out which plugin and stop it

**Comment by jonthesquirrel** [comment]
since grey, mamimi, and mario have done stuff, don't reset entire world but fix things

**Comment by jonthesquirrel** [comment]
add /home in survival

**Comment by jonthesquirrel** [comment]
inventory doesn't keep when dying for non-admin

**Comment by jonthesquirrel** [comment]
moved survival into its own vanilla server connected with bungee, and did some bungee innovations.
